version: '3.7'

services:
  swaggerui:
    image: swaggerapi/swagger-ui:v3.22.1
    network_mode: bridge
    volumes:
      - ./docs:/usr/share/nginx/html/docs
    ports:
      - "80:8080"
    environment:
      - URLS_PRIMARY_NAME=PETSTORE
      - URLS
    